---
title: "dataViz"
author: "Najeeb Khan, Hafik Arhan, Swaraj Oturkar, Elif Erbil"
date: "12/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/Google Drive/TUM Session/Semester One/Data Visualisation in R/')

```

### Getting Data 
```{r echo=FALSE, include=FALSE}
library(data.table)
library(knitr)
library(ggplot2)
library(reshape)
```
```{r echo=TRUE}
genotype_file <- 'Data/eqtl/genotype.txt'
growth_file <- 'Data/eqtl/growth.txt'
genotype <- as.data.table(read.delim(genotype_file))
growth <- as.data.table(read.delim(growth_file))
```
### Checking the integrity of the data in both of the tables

```{r echo=TRUE}
## Genotype Data
names <- c("strain")
for(i in 1:1000)
{
  names <- c(names, paste("mrk", i, sep = "_"))
}
colnames(genotype) <- names

### Calculating the proportion of Wild Isolate and Lab Strain
genotype[, labProp := apply(genotype, MARGIN = 1, FUN = function(row) mean(grepl(unname(unlist(row)), pattern = 'Lab strain')))]

genotype[, wildProp := apply(genotype, MARGIN = 1, FUN = function(row) mean(grepl(unname(unlist(row)), pattern = 'Wild isolate')))]

## Growth Data

### Checking the column class
sapply(growth, class)

### Melting the data to make it tidy
growth_melt <- melt(growth, id.vars = 'strain', variable.name = 'env', value.name = 'rate')
genotype_melt <- melt(genotype, id.vars = 'strain', variable.name = 'marker', value.name = 'genotype')
genotype_melt[,marker:=gsub("mrk_","",marker)]
### Plotting boxplots to recognize any outliers
ggplot(growth_melt, aes(env, rate)) + geom_boxplot() + theme_minimal() +
  labs(title = "Visualisation of Growth Data") +
  xlab("Environment") +
  ylab("Rate of Growth")

```

### Getting insight into how proportion of each parent strain effects the growth
We investigate how the proportion of parent strain (from Wild Isolate and Lab Strain) is responsible for effecting the growth in a particular medium.

```{r echo=TRUE}
## Merging the two datasets on the basis of segregants
growth_geno <- merge(genotype[, c(1, 1002, 1003)], growth)

## Melting the merged table
growth_geno_melt <- melt(growth_geno, id.vars = c('strain', 'labProp', 'wildProp'), variable.name = 'env', value.name = 'rate')

## PLotting the data points as scatterplots distributed over environments
ggplot(growth_geno_melt, aes(x = wildProp, y=rate)) + geom_point() + theme_minimal() +
  facet_wrap(~env)

ggplot(growth_geno_melt, aes(x = labProp, y=rate)) + geom_point() + theme_minimal() +
  facet_wrap(~env)

## Growth and Marker plots

### Merging growth and genotype data with markers
growth_marker <- merge(genotype, growth)
growth_marker_melt <- melt(growth_marker, id.vars = colnames(growth_marker)[1:1003], variable.name = "env", value.name="rate")

### Melting the markers in one column to make data tidy
growth_marker_melt <- melt(growth_marker_melt, id.vars = c("strain", "env", "rate", "labProp", "wildProp"), variable.name = "marker_number", value.name = "parent_strain")

### Cleaning the marker number column
growth_marker_melt[, marker_number := as.integer(gsub("mrk_", "", marker_number))]

### Plotting marker number with the mean of the rate in each of those markers
growth_marker_melt[, mean_growth_per_marker := mean(rate, na.rm = T), by=marker_number]

ggplot(growth_marker_melt, aes(x = marker_number, y=mean_growth_per_marker)) +  geom_line()+ theme_minimal() + facet_wrap(~env) +
  labs(title = "Variation of growth with the marker") + xlab("Marker Number") + ylab("Rate of Growth")

```